using System;
using UnityEngine;
using SpaceGame.World.Streaming;

namespace SpaceGame.World
{
    [CreateAssetMenu(fileName = "WorldStreamingConfig", menuName = "World Streaming/Config")]
    public class WorldStreamingConfig : ScriptableObject
    {
        [Header("Grid Settings")]
        [Tooltip("Size of each chunk in world units (X = width, Y = depth)")]
        public Vector2 chunkSize = new Vector2(256f, 256f);

        [Tooltip("Number of chunks in each direction (X columns, Y rows)")]
        public Vector2Int gridDimensions = new Vector2Int(4, 4);

        [Tooltip("World-space position of the grid's bottom-left corner")]
        public Vector3 worldOrigin = Vector3.zero;

        [Header("Streaming Settings")]
        [Tooltip("How many chunks around the player to keep loaded (1 = 3x3 grid, 2 = 5x5 grid)")]
        [Range(1, 4)]
        public int loadRadius = 1;

        [Tooltip("Seconds to wait before unloading a chunk no player needs (prevents thrashing)")]
        public float unloadGracePeriod = 10f;

        [Tooltip("How far past the grid's edge a position still streams the world. Inside this " +
                 "band the nearest edge chunks stay loaded, so anything that leaves the map — a " +
                 "dune foil at 45 m/s is berthed 200 m from the east edge — keeps the ground it " +
                 "came from and can sail back onto it. Beyond it the position counts as another " +
                 "place entirely and holds nothing open; the minigame arena is ~16.5 km out.")]
        public float offWorldDistance = 2000f;

        [Tooltip("Seconds of travel the streamer looks ahead of a moving tracker, so chunks start " +
                 "loading before it arrives. Clamped to one chunk of travel. At walking pace this " +
                 "changes nothing; it exists for vehicles fast enough to outrun a scene load.")]
        public float streamLookaheadSeconds = 2f;

        /// <summary>The grid as pure geometry. All coordinate maths lives there and is unit tested.</summary>
        public ChunkGrid Grid => new ChunkGrid(worldOrigin, chunkSize, gridDimensions);

        [Header("Chunk Data (auto-generated by WorldChunker)")]
        public ChunkInfo[] chunks;

        /// <summary>
        /// Returns true if <paramref name="worldPos"/> falls within the grid's world-space bounds.
        /// WorldToChunkCoord clamps out-of-bounds positions to the nearest edge chunk rather than
        /// signaling invalidity, so callers that need to distinguish "outside the world" (e.g. a
        /// scene deliberately placed off-grid) from "inside the world" must check this first.
        /// </summary>
        public bool IsWithinGrid(Vector3 worldPos) => Grid.Contains(worldPos);

        /// <summary>
        /// Converts a world position to the chunk grid coordinate that contains it.
        /// </summary>
        public Vector2Int WorldToChunkCoord(Vector3 worldPos) => Grid.ToCoord(worldPos);

        /// <summary>
        /// The chunk a position should stream around, or false when it is far enough outside the
        /// grid to be another place entirely (see <see cref="offWorldDistance"/>). This — not
        /// <see cref="IsWithinGrid"/> — is what streaming decisions must ask: a player past the
        /// edge of the map still needs the world they came from kept loaded.
        /// </summary>
        public bool TryGetStreamingCoord(Vector3 worldPos, out Vector2Int coord)
            => Grid.TryGetStreamingCoord(worldPos, offWorldDistance, out coord);

        /// <summary>Where a tracker moving at this velocity will be in <see cref="streamLookaheadSeconds"/>.</summary>
        public Vector3 PredictAhead(Vector3 worldPos, Vector3 velocity)
            => Grid.PredictAhead(worldPos, velocity, streamLookaheadSeconds);

        /// <summary>
        /// Gets the world-space origin for the chunk at the given grid coordinate.
        /// </summary>
        public Vector3 ChunkToWorldPosition(Vector2Int coord) => Grid.ChunkToWorldPosition(coord);

        /// <summary>
        /// Gets the ChunkInfo for a given grid coordinate, or null if out of bounds.
        /// </summary>
        public ChunkInfo? GetChunk(Vector2Int coord)
        {
            if (chunks == null) return null;

            foreach (var chunk in chunks)
            {
                if (chunk.gridCoord == coord)
                    return chunk;
            }

            return null;
        }

        /// <summary>
        /// Returns true if the coordinate is within the grid bounds.
        /// </summary>
        public bool IsValidCoord(Vector2Int coord) => Grid.IsValidCoord(coord);
    }

    [Serializable]
    public struct ChunkInfo
    {
        public Vector2Int gridCoord;
        public string sceneName;
        public string scenePath; // full asset path, e.g. Assets/Game/Scenes/World/Chunks/Chunk_0_0.unity
        public Bounds worldBounds;
        public bool hasTerrain;
    }
}
