// Getting AgentGroundConform onto every agent that needs it, and keeping it there.
//
// Four of the ten agent prefabs are generated by a builder that overwrites the prefab wholesale, so
// a component added by hand disappears the next time somebody rebuilds -- which is how the Golem
// lost its SaveableEntity. Ensure() is therefore called from BOTH ends: from the menu item here,
// which fixes the six prefabs nobody generates, and from inside each builder.
using UnityEditor;
using UnityEngine;
using UnityEngine.AI;
using SpaceGame.Agents;

namespace SpaceGame.EditorTools
{
    public static class AgentGroundConformWiring
    {
        private const string AgentPrefabRoot = "Assets/Game/Prefabs/agents";

        /// <summary>
        /// How much of the slope a two-legged body takes on.
        ///
        /// <para>
        /// Low, and deliberately so. A walking biped does not lie along the hillside — it holds its
        /// torso near vertical and spends the slope in its legs, so leaning it over the way a
        /// many-legged body leans reads as falling rather than as walking. Nine of this project's
        /// ten NavMesh agents are bipeds: the Nomad and its BountyHunter variant, all four
        /// PatrolRobots, the DeathmatchBot, the Golem (`Bone_Thigh/Shin/Foot_L/R` and nothing else)
        /// and the DuneRat, whose bone names claim a quadruped but whose forelimbs are 0.29 m
        /// against a 0.99 m hind chain and rest clear of the ground.
        /// </para>
        /// </summary>
        public const float BipedSlopeFollow = 0.35f;

        /// <summary>
        /// How much of the slope a body with legs on every side takes on. Nearly all of it: every
        /// foot is on the hillside, so the shell hugging it is what standing on it looks like.
        /// The Vrescal hexapod is the only agent in this project that qualifies.
        /// </summary>
        public const float ManyLeggedSlopeFollow = 0.8f;

        /// <summary>
        /// Prefab file names whose agent walks on more than two legs. A list rather than something
        /// derived from the rig because it is one entry: counting foot bones to rediscover a fact
        /// that fits on one line would be the more fragile of the two.
        /// </summary>
        private static readonly string[] ManyLegged = { "Vrescal" };

        /// <summary>
        /// Adds <see cref="AgentGroundConform"/> to <paramref name="root"/> if it drives a
        /// NavMeshAgent and does not have one yet. Returns whether anything changed, so a caller
        /// can skip a pointless prefab save.
        ///
        /// <para>
        /// <paramref name="slopeFollow"/> is applied only on the frame the component is ADDED, so
        /// re-running this never overwrites a value somebody has since tuned in the Inspector.
        /// </para>
        /// </summary>
        public static bool Ensure(GameObject root, float slopeFollow = BipedSlopeFollow)
        {
            if (root == null) return false;
            if (root.GetComponent<NavMeshAgent>() == null) return false;
            if (root.GetComponent<AgentGroundConform>() != null) return false;

            var conform = root.AddComponent<AgentGroundConform>();

            var so = new SerializedObject(conform);
            SerializedProperty property = so.FindProperty("slopeFollow");
            if (property == null)
            {
                Debug.LogError("[AgentGroundConformWiring] AgentGroundConform has no slopeFollow " +
                               "field to set. The component was added with its own default.", root);
                return true;
            }

            property.floatValue = slopeFollow;
            so.ApplyModifiedPropertiesWithoutUndo();
            return true;
        }

        [MenuItem("Tools/SpaceGame/Agents/Wire Ground Conform")]
        public static void WireAll()
        {
            int changed = 0, seen = 0;

            foreach (string guid in AssetDatabase.FindAssets("t:Prefab", new[] { AgentPrefabRoot }))
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                var asset = AssetDatabase.LoadAssetAtPath<GameObject>(path);
                if (asset == null || asset.GetComponent<NavMeshAgent>() == null) continue;

                seen++;
                GameObject contents = PrefabUtility.LoadPrefabContents(path);
                try
                {
                    if (!Ensure(contents, SlopeFollowFor(path))) continue;

                    PrefabUtility.SaveAsPrefabAsset(contents, path, out bool saved);

                    // A read-only AssetDatabase discards a prefab save and says nothing at all.
                    if (!saved)
                    {
                        Debug.LogError($"[AgentGroundConformWiring] Could not save {path}. " +
                                       "The AssetDatabase refused the write.");
                        continue;
                    }

                    changed++;
                    Debug.Log($"[AgentGroundConformWiring] Added AgentGroundConform to {path}");
                }
                finally
                {
                    PrefabUtility.UnloadPrefabContents(contents);
                }
            }

            AssetDatabase.SaveAssets();
            Debug.Log($"[AgentGroundConformWiring] {changed} of {seen} agent prefabs updated.");
        }

        private static float SlopeFollowFor(string prefabPath)
        {
            string name = System.IO.Path.GetFileNameWithoutExtension(prefabPath);
            foreach (string many in ManyLegged)
            {
                if (name.StartsWith(many, System.StringComparison.OrdinalIgnoreCase))
                    return ManyLeggedSlopeFollow;
            }
            return BipedSlopeFollow;
        }
    }
}
