"""Survey the model library and write an index of everything in it.

Run from the repository root:

    python scripts/index_library.py --models-dir "Assets/Models/_Source~"

Opens every .blend under the library headless, records its collections,
objects, dimensions, materials and armatures, then writes:

    <models-dir>/library_index.json   machine-readable
    <models-dir>/LIBRARY.md           human-readable

Read the index before planning any new model. It is the only reliable way to
know what already exists and therefore what you should be reusing rather than
rebuilding.

This file is dual-purpose: run under plain Python it drives Blender, and run
under Blender (`blender --background file.blend --python index_library.py`)
it acts as the inspector for the file it was given.
"""

import json
import os
import sys

try:
    import bpy
    IN_BLENDER = True
except ImportError:
    IN_BLENDER = False


MARKER_START = "###BLENDINFO_START###"
MARKER_END = "###BLENDINFO_END###"


# --------------------------------------------------------------------------
# Inspector half — runs inside Blender against the currently open file
# --------------------------------------------------------------------------

def inspect_open_file():
    def rounded(vec):
        return [round(float(v), 4) for v in vec]

    collections = []
    for coll in bpy.data.collections:
        collections.append({
            "name": coll.name,
            "objects": [o.name for o in coll.objects],
            "children": [c.name for c in coll.children],
        })

    objects = []
    for obj in bpy.data.objects:
        entry = {
            "name": obj.name,
            "type": obj.type,
            "location": rounded(obj.location),
            "scale": rounded(obj.scale),
            "collections": [c.name for c in obj.users_collection],
        }
        if obj.type == 'MESH':
            entry["dimensions"] = rounded(obj.dimensions)
            entry["vertices"] = len(obj.data.vertices)
            entry["polygons"] = len(obj.data.polygons)
            entry["materials"] = [m.name for m in obj.data.materials if m]
            entry["modifiers"] = [m.name for m in obj.modifiers]
        if obj.type == 'ARMATURE':
            entry["bones"] = [b.name for b in obj.data.bones]
        objects.append(entry)

    materials = sorted({m.name for m in bpy.data.materials})
    linked = sorted({
        lib.filepath for lib in bpy.data.libraries if lib.filepath
    })

    # Names Blender auto-suffixed (Cube.003) signal unfinished work
    unnamed = [
        o.name for o in bpy.data.objects
        if len(o.name) > 4 and o.name[-4] == "." and o.name[-3:].isdigit()
    ]

    return {
        "collections": collections,
        "objects": objects,
        "materials": materials,
        "linked_libraries": linked,
        "auto_suffixed_names": unnamed,
    }


# --------------------------------------------------------------------------
# Driver half — runs under plain Python
# --------------------------------------------------------------------------

def find_blender():
    import shutil
    for candidate in ("blender", "/Applications/Blender.app/Contents/MacOS/Blender"):
        found = shutil.which(candidate) or (
            candidate if os.path.exists(candidate) else None
        )
        if found:
            return found
    return None


def inspect_file(blender, blend_path):
    import subprocess
    result = subprocess.run(
        [blender, "--background", blend_path, "--python", os.path.abspath(__file__)],
        capture_output=True, text=True, timeout=180,
    )
    out = result.stdout
    if MARKER_START not in out or MARKER_END not in out:
        return {"error": (result.stderr or out or "no output").strip()[-500:]}
    raw = out.split(MARKER_START, 1)[1].split(MARKER_END, 1)[0]
    try:
        return json.loads(raw)
    except json.JSONDecodeError as exc:
        return {"error": f"could not parse inspector output: {exc}"}


def write_markdown(index, path, models_dir):
    lines = [
        "# Model Library",
        "",
        "Generated by `scripts/index_library.py`. Do not edit by hand.",
        "",
        "Check here before building anything — reusing an existing component",
        "always beats creating a near-duplicate.",
        "",
    ]

    components = {k: v for k, v in index.items() if k.startswith("components/")}
    models = {k: v for k, v in index.items() if k.startswith("models/")}
    other = {
        k: v for k, v in index.items()
        if k not in components and k not in models
    }

    lines.append(
        f"**{len(components)} component file(s)**, **{len(models)} model file(s)**."
    )
    lines.append("")

    for title, group in (
        ("Components", components), ("Models", models), ("Other", other)
    ):
        if not group:
            continue
        lines += [f"## {title}", ""]
        for rel_path in sorted(group):
            data = group[rel_path]
            lines.append(f"### `{rel_path}`")
            lines.append("")
            if "error" in data:
                lines += [f"> Could not read: {data['error']}", ""]
                continue

            top_colls = [
                c["name"] for c in data["collections"]
                if not any(c["name"] in other_c["children"]
                           for other_c in data["collections"])
            ]
            if top_colls:
                lines.append(f"Variations / collections: {', '.join(f'`{c}`' for c in top_colls)}")
                lines.append("")

            meshes = [o for o in data["objects"] if o["type"] == 'MESH']
            if meshes:
                lines += [
                    "| Object | Dimensions (m) | Polys | Materials |",
                    "|---|---|---|---|",
                ]
                for m in meshes:
                    dims = " x ".join(str(d) for d in m.get("dimensions", []))
                    mats = ", ".join(m.get("materials", [])) or "—"
                    lines.append(
                        f"| `{m['name']}` | {dims} | {m.get('polygons', 0)} | {mats} |"
                    )
                lines.append("")

            arms = [o for o in data["objects"] if o["type"] == 'ARMATURE']
            for a in arms:
                lines.append(
                    f"Armature `{a['name']}`: {len(a.get('bones', []))} bone(s) — "
                    + ", ".join(f"`{b}`" for b in a.get("bones", []))
                )
                lines.append("")

            if data.get("auto_suffixed_names"):
                lines += [
                    "> Unfinished: auto-suffixed names present — "
                    + ", ".join(f"`{n}`" for n in data["auto_suffixed_names"]),
                    "",
                ]

    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))


def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--models-dir", default="Assets/Models/_Source~")
    parser.add_argument("--blender", default=None, help="Path to the Blender executable")
    args = parser.parse_args()

    models_dir = os.path.abspath(args.models_dir)
    if not os.path.isdir(models_dir):
        raise SystemExit(
            f"No library at {models_dir}. Create it before indexing — see SKILL.md."
        )

    blender = args.blender or find_blender()
    if not blender:
        raise SystemExit(
            "Blender executable not found. Pass --blender /path/to/blender."
        )

    blend_files = []
    for root, _dirs, files in os.walk(models_dir):
        for name in sorted(files):
            if name.endswith(".blend"):
                blend_files.append(os.path.join(root, name))

    index = {}
    for path in blend_files:
        rel = os.path.relpath(path, models_dir)
        print(f"  inspecting {rel} ...", flush=True)
        index[rel.replace(os.sep, "/")] = inspect_file(blender, path)

    json_path = os.path.join(models_dir, "library_index.json")
    with open(json_path, "w", encoding="utf-8") as fh:
        json.dump(index, fh, indent=2)

    md_path = os.path.join(models_dir, "LIBRARY.md")
    write_markdown(index, md_path, models_dir)

    errors = sum(1 for v in index.values() if "error" in v)
    print(f"\nIndexed {len(index)} file(s), {errors} error(s)")
    print(f"  {json_path}")
    print(f"  {md_path}")


if IN_BLENDER:
    print(MARKER_START)
    print(json.dumps(inspect_open_file()))
    print(MARKER_END)
elif __name__ == "__main__":
    main()
