// The station table of docs/AI/systems/StationTable.md, written from the data: one row per kind of spot and the cue it holds, with
// the props that carry it, whether it names a target, the reach its clips were measured at, the loops that fit, the tools those
// clips are made for, who works there and what they carry, and a status derived from all of that. A hand-kept table would be wrong
// the first time a spot is re-pointed; this one is regenerated, and StationTableTests fails when the document is stale.
//
// Run from: Tools > SpaceGame > Residents > Write Station Table
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using SpaceGame.EditorTools;
using SpaceGame.Items;
using SpaceGame.Presentation;
using SpaceGame.World;
using UnityEditor;
using UnityEngine;

namespace SpaceGame.Agents.Residents.EditorTools
{
    public static class StationTable
    {
        public const string DocPath = "docs/AI/systems/StationTable.md";
        public const string Begin = "<!-- STATIONS:BEGIN generated by Tools > SpaceGame > Residents > Write Station Table -->";
        public const string End = "<!-- STATIONS:END -->";

        private const int PropsShown = 5;
        private const string SpotFolder ="Assets/Game/ScriptableObjects/Settlements/Spots";
        private const string ArchetypeFolder = "Assets/Game/ScriptableObjects/Residents/Archetypes";
        private static readonly string[] PropFolders =
        {
            "Assets/Game/Prefabs/Environment/Decorations",
            "Assets/Game/Prefabs/Environment/Structures/NomadSettlement",
        };

        /// <summary>One kind of spot as it is held: the use, the cue it holds on these props, and everything the contract asks about it.</summary>
        public sealed class Station
        {
            public SpotUse Use;
            public CharacterCue Cue;
            public List<string> Props = new List<string>();
            public int Spots, WithTarget;
            public float NearestStand = float.MaxValue, FarthestStand;
            public List<ResidentArchetype> Workers = new List<ResidentArchetype>();
            public List<CharacterAction> Loops = new List<CharacterAction>();
            public string Status;
        }

        [MenuItem("Tools/SpaceGame/Residents/Write Station Table")]
        private static void WriteMenu() => Debug.Log(Write());

        /// <summary>Rewrites the table in the document. The report names the document, or says it was already current.</summary>
        public static string Write()
        {
            string text = File.ReadAllText(DocPath);
            string updated = Replace(text, Markdown(Stations()));
            if (updated == text) return "[Stations] " + DocPath + " is already current.";

            File.WriteAllText(DocPath, updated);
            return "[Stations] wrote the station table into " + DocPath + ".";
        }

        /// <summary>The document with its generated table replaced by <paramref name="table"/>.</summary>
        public static string Replace(string document, string table)
        {
            int begin = document.IndexOf(Begin, System.StringComparison.Ordinal);
            int end = document.IndexOf(End, System.StringComparison.Ordinal);
            if (begin < 0 || end < begin) throw new InvalidDataException(DocPath + " has no station table markers.");

            return document.Substring(0, begin) + Begin + "\n\n" + table + "\n" + document.Substring(end);
        }

        /// <summary>The table the data says today.</summary>
        public static List<Station> Stations()
        {
            var uses = AssetDatabase.FindAssets("t:SpotUse", new[] { SpotFolder })
                .Select(g => AssetDatabase.LoadAssetAtPath<SpotUse>(AssetDatabase.GUIDToAssetPath(g))).OrderBy(u => u.name).ToList();
            var archetypes = AssetDatabase.FindAssets("t:ResidentArchetype", new[] { ArchetypeFolder })
                .Select(g => AssetDatabase.LoadAssetAtPath<ResidentArchetype>(AssetDatabase.GUIDToAssetPath(g))).OrderBy(a => a.name).ToList();
            var actions = HumanoidControllerBuilder.CollectActions();
            var stations = new Dictionary<(SpotUse, CharacterCue), Station>();

            foreach (SpotUse use in uses) Get(stations, use, use.holdCue);

            foreach (string path in AssetDatabase.FindAssets("t:Prefab", PropFolders).Select(AssetDatabase.GUIDToAssetPath).OrderBy(p => p))
            {
                GameObject root = PrefabUtility.LoadPrefabContents(path);
                try
                {
                    foreach (SettlementSpot spot in root.GetComponentsInChildren<SettlementSpot>(true))
                    {
                        if (spot.Use == null) continue;

                        Station station = Get(stations, spot.Use, spot.HoldCue);
                        string prop = Path.GetFileNameWithoutExtension(path).Replace("Deco_", "");
                        if (!station.Props.Contains(prop)) station.Props.Add(prop);
                        station.Spots++;
                        if (!spot.HasTarget) continue;

                        station.WithTarget++;
                        Vector3 toFace = spot.FacePoint - spot.Position;
                        float distance = new Vector2(toFace.x, toFace.z).magnitude;
                        station.NearestStand = Mathf.Min(station.NearestStand, distance);
                        station.FarthestStand = Mathf.Max(station.FarthestStand, distance);
                    }
                }
                finally
                {
                    PrefabUtility.UnloadPrefabContents(root);
                }
            }

            foreach (Station station in stations.Values)
            {
                station.Workers = archetypes.Where(a => a.post == station.Use).ToList();
                if (station.Cue != null)
                    station.Loops = actions.Where(a => a.Loops && a.Cues.Contains(station.Cue) && (a.Fits(BodyPosture.Standing) || a.Fits(BodyPosture.Seated))).ToList();
                station.Status = StatusOf(station);
            }

            return stations.Values.OrderBy(s => s.Use.name).ThenBy(s => s.Cue != null ? s.Cue.name : "").ToList();
        }

        private static Station Get(Dictionary<(SpotUse, CharacterCue), Station> stations, SpotUse use, CharacterCue cue)
        {
            if (!stations.TryGetValue((use, cue), out Station station)) stations[(use, cue)] = station = new Station { Use = use, Cue = cue };
            return station;
        }

        /// <summary>Why a station is or is not right: no cue (stands), a cue no loop answers, a worker without the tool the clips are made for, else ok.</summary>
        public static string StatusOf(Station station)
        {
            if (station.Cue == null) return station.Use.role == SpotRole.Errand ? "stands (an errand's stop)" : "stands (no clip yet)";
            if (station.Loops.Count == 0) return "MISSING CLIP";

            var missing = new List<string>();
            foreach (ResidentArchetype worker in station.Workers)
                if (station.Cue.Tools.Count > 0 && !Carries(worker, station.Cue.Tools))
                    missing.Add(worker.name + " carries " + Carried(worker));
            return missing.Count == 0 ? "ok" : "TOOL MISMATCH: " + string.Join("; ", missing);
        }

        private static bool Carries(ResidentArchetype worker, IReadOnlyList<InventoryItem> tools) =>
            (worker.heldItem != null && tools.Contains(worker.heldItem)) || (worker.beltItems != null && worker.beltItems.Any(item => tools.Contains(item)));

        private static string Carried(ResidentArchetype worker)
        {
            var items = new List<string>();
            if (worker.heldItem != null) items.Add(worker.heldItem.name.Replace("Tool_", ""));
            if (worker.beltItems != null) items.AddRange(worker.beltItems.Where(i => i != null).Select(i => i.name.Replace("Tool_", "")));
            return items.Count == 0 ? "nothing" : string.Join("+", items);
        }

        public static string Markdown(IEnumerable<Station> stations)
        {
            var text = new StringBuilder();
            text.AppendLine("| Spot use | Role | Props | Target | Stand to target | Cue | Loops that fit | Tools the clips assume | Works here (carries) | Status |");
            text.AppendLine("| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |");
            foreach (Station s in stations)
            {
                string stand = s.WithTarget == 0 ? "-" : F(s.NearestStand) + (s.FarthestStand - s.NearestStand > 0.05f ? "-" + F(s.FarthestStand) : "") + " m" + Reach(s);
                string props = s.Props.Count == 0 ? "-" : string.Join(", ", s.Props.Take(PropsShown)) + (s.Props.Count > PropsShown ? " (+" + (s.Props.Count - PropsShown) + ")" : "");
                string cue = s.Cue != null ? s.Cue.name : "-";
                string loops = s.Loops.Count == 0 ? "-" : string.Join(", ", s.Loops.Take(4).Select(a => a.name)) + (s.Loops.Count > 4 ? " (+" + (s.Loops.Count - 4) + ")" : "");
                string tools = s.Cue == null ? "-" : ResidentHandsRule.EmptyHandsFor(s.Cue) ? "empty hands" : s.Cue.Tools.Count == 0 ? "any" : string.Join(", ", s.Cue.Tools.Select(t => t.name.Replace("Tool_", "")));
                string workers = s.Workers.Count == 0 ? "-" : string.Join("; ", s.Workers.Select(w => w.name + " (" + Carried(w) + ")"));
                text.AppendLine("| " + s.Use.name + " | " + s.Use.role + (s.Use.seated ? ", sits" : "") + " | " + props + " | " + s.WithTarget + "/" + s.Spots +
                                " | " + stand + " | " + cue + " | " + loops + " | " + tools + " | " + workers + " | " + s.Status + " |");
            }
            return text.ToString();
        }

        private static string Reach(Station s)
        {
            var actions = HumanoidControllerBuilder.CollectActions().Where(a => s.Cue != null && a.Cues.Contains(s.Cue)).ToList();
            return StationStand.TryForwardReach(actions, out float forward, out _) ? ", reach " + F(forward) + " m" : "";
        }

        private static string F(float value) => value.ToString("0.0", System.Globalization.CultureInfo.InvariantCulture);
    }
}
