"""Measure Appa's flank into the table `saddle.py` wraps its leather onto.

    blender --background --python models/gear/measure_appa_flank.py

Writes `models/gear/appa_surface.py`. Read-only on `appa.blend`.

The saddle's panel is fitted with a downward cast (`BACK` in saddle.py), which
knows only his top surface. Anything that hangs off his sides needs the other
axis: how wide he is at a given height. This bakes that as a grid so `saddle.py`
can shrink-wrap onto it without opening his file.
"""
import os
import sys

import bpy
import mathutils
from mathutils.bvhtree import BVHTree

HERE = os.path.dirname(os.path.abspath(__file__))
APPA = os.path.join(os.path.dirname(HERE), "creatures", "appa.blend")
DST = os.path.join(HERE, "appa_surface.py")

# The saddle's own frame, and the span its leather can reach over.
ORIGIN_X, ORIGIN_Z = 1.62, 0.329
Y0, Y1, NY = -0.85, 0.85, 35        # fore/aft of the saddle centre
Z0, Z1, NZ = -1.00, 0.30, 27        # below/above his spine


def main():
    bpy.ops.wm.open_mainfile(filepath=APPA)
    dg = bpy.context.evaluated_depsgraph_get()

    tris, verts = [], []
    for ob in bpy.context.scene.objects:
        if ob.type != 'MESH' or ob.hide_get() or ob.hide_render:
            continue
        me = ob.evaluated_get(dg).to_mesh()
        me.calc_loop_triangles()
        base = len(verts)
        mw = ob.matrix_world
        verts.extend([mw @ v.co for v in me.vertices])
        tris.extend([[i + base for i in t.vertices] for t in me.loop_triangles])
        ob.evaluated_get(dg).to_mesh_clear()
    bvh = BVHTree.FromPolygons(verts, tris)

    ys = [Y0 + (Y1 - Y0) * i / float(NY - 1) for i in range(NY)]
    zs = [Z0 + (Z1 - Z0) * i / float(NZ - 1) for i in range(NZ)]

    grid = []
    for sy in ys:
        row = []
        for sz in zs:
            # Cast in from both sides and keep the wider: he is close to
            # symmetric but not exactly, and one saddle serves both flanks.
            w = 0.0
            for sgn in (1.0, -1.0):
                hit = bvh.ray_cast(
                    mathutils.Vector((ORIGIN_X + sy, sgn * 5.0, ORIGIN_Z + sz)),
                    mathutils.Vector((0.0, -sgn, 0.0)), 10.0)
                if hit[0] is not None:
                    w = max(w, 5.0 - hit[3])
            row.append(w)
        grid.append(row)

    with open(DST, "w") as fh:
        fh.write('"""Appa\'s flank, measured. GENERATED by measure_appa_flank.py '
                 '-- do not hand-edit.\n\n'
                 'HALF_WIDTH[i][j] is his half-width at (Y[i], Z[j]) in saddle space,\n'
                 'or 0.0 where the cast missed him entirely.\n"""\n\n')
        fh.write("ORIGIN_X = %.4f\nORIGIN_Z = %.4f\n\n" % (ORIGIN_X, ORIGIN_Z))
        fh.write("Y = [%s]\n\n" % ", ".join("%.4f" % v for v in ys))
        fh.write("Z = [%s]\n\n" % ", ".join("%.4f" % v for v in zs))
        fh.write("HALF_WIDTH = [\n")
        for sy, row in zip(ys, grid):
            fh.write("    [%s],  # y=%+.3f\n"
                     % (", ".join("%.4f" % v for v in row), sy))
        fh.write("]\n")

    solid = sum(1 for r in grid for v in r if v > 0)
    print("  wrote %s" % DST)
    print("  %d x %d grid, %d of %d samples hit him" % (NY, NZ, solid, NY * NZ))


main()
