using UnityEngine;

namespace SpaceGame.World
{
    /// <summary>
    /// THE footprint authority for an AREA terrain feature. One serializable object the
    /// <c>TerrainFeatureSpawner</c> owns, replacing the old scattered fields (box half-extents +
    /// footprint shape enum + complexity dial + loose polygon).
    ///
    /// It carries:
    ///   • The box dimensions — Width (X), Height (Y, vertical extent), Breadth (Z).
    ///   • The <see cref="FootprintMode"/> — hand-edited Polygon or generated Noise.
    ///   • The raw <see cref="FeaturePolygon"/> outline (hand-edited in Polygon mode, regenerated by
    ///     <see cref="FootprintNoise"/> in Noise mode).
    ///   • The <see cref="FootprintNoise"/> knob block, used only in Noise mode.
    ///
    /// Everything downstream — every feature, the mesher, the bounds — goes through ONE call:
    /// <see cref="SignedDistanceInside"/>. Callers never branch on the mode. The mesher reads
    /// <see cref="ComputeLocalBounds"/>. That single seam is what keeps all 14 features untouched
    /// while the footprint internals are rewritten.
    ///
    /// Determinism: in Noise mode the outline is a pure function of (box, seed, knobs); regenerating
    /// is idempotent, so a baked feature reproduces exactly.
    /// </summary>
    [System.Serializable]
    public class FeatureFootprint
    {
        // -------------------------------------------------------------------------
        // Box dimensions — Width / Height / Breadth (full sizes, in metres).
        // Stored as full extents (not half-extents) because designers think in
        // "this feature is 80 m wide", not "40 m half-extent".
        // -------------------------------------------------------------------------

        [Tooltip("Footprint size along local X, in metres. The Noise outline fills this; the Polygon " +
                 "outline is seeded from it.")]
        [Min(2f)] public float width = 80f;

        [Tooltip("Vertical extent of the feature along local Y, in metres. This is the meshing band " +
                 "height — how tall the feature can rise / how deep it can carve. It does NOT affect " +
                 "the 2D outline shape.")]
        [Min(2f)] public float height = 50f;

        [Tooltip("Footprint size along local Z, in metres. The Noise outline fills this; the Polygon " +
                 "outline is seeded from it.")]
        [Min(2f)] public float breadth = 80f;

        // -------------------------------------------------------------------------
        // Mode + outline data.
        // -------------------------------------------------------------------------

        [Tooltip("How the outline is authored.\n• Polygon — drag the vertices in the Scene view.\n" +
                 "• Noise — the outline is generated from the noise knobs below.")]
        public FootprintMode mode = FootprintMode.Polygon;

        [Tooltip("The raw closed outline. Hand-edited in Polygon mode; regenerated from the noise " +
                 "knobs in Noise mode. Edited visually in the Scene view, never as raw fields.")]
        [HideInInspector] public FeaturePolygon polygon = new FeaturePolygon();

        [Tooltip("Explicit noise knobs used only in Noise mode — lobe frequency/amplitude, detail " +
                 "octaves/gain, irregularity, corner sharpness.")]
        public FootprintNoise noise = new FootprintNoise();

        // -------------------------------------------------------------------------
        // Derived values.
        // -------------------------------------------------------------------------

        /// <summary>Box half-extents (X = half-Width, Y = half-Height, Z = half-Breadth). Many callers
        /// and the Scene-view handles work in half-extents, so this is the conversion point.</summary>
        public Vector3 BoxHalfExtents => new Vector3(
            Mathf.Max(1f, width * 0.5f),
            Mathf.Max(1f, height * 0.5f),
            Mathf.Max(1f, breadth * 0.5f));

        /// <summary>True while the outline is generated and therefore NOT hand-editable.</summary>
        public bool IsGenerated => mode == FootprintMode.Noise;

        // -------------------------------------------------------------------------
        // Lifecycle — keep the outline consistent with the mode.
        // -------------------------------------------------------------------------

        /// <summary>
        /// Ensures the outline polygon is valid and consistent with the current mode. Call before any
        /// query or bake. In Noise mode it regenerates the outline from the box + knobs (idempotent and
        /// deterministic); in Polygon mode it seeds an ellipse the first time so the feature is always
        /// editable.
        /// </summary>
        public void Refresh(int seed)
        {
            polygon ??= new FeaturePolygon();
            noise ??= new FootprintNoise();

            if (mode == FootprintMode.Noise)
            {
                noise.Generate(polygon.vertices, BoxHalfExtents, seed);
            }
            else if (!polygon.IsValid)
            {
                polygon.ResetToEllipse(BoxHalfExtents);
            }
        }

        /// <summary>Bakes the current generated outline into editable Polygon-mode vertices, so a
        /// designer can start from a noise shape and then hand-tweak it. No-op if already Polygon mode.</summary>
        public void ConvertNoiseToPolygon(int seed)
        {
            if (mode != FootprintMode.Noise) return;
            Refresh(seed);                 // make sure the outline reflects the current knobs
            mode = FootprintMode.Polygon;  // the now-frozen vertices become hand-editable
        }

        // -------------------------------------------------------------------------
        // Queries — the single seam every feature goes through.
        // -------------------------------------------------------------------------

        /// <summary>
        /// Signed distance from a feature-local (x, z) point to the footprint outline: POSITIVE metres
        /// inside, NEGATIVE outside. THE call every area feature feeds into
        /// <see cref="TerrainNoiseHelper.OverlapWeight"/>. Falls back to the Width × Breadth box
        /// rectangle when the polygon is somehow empty, so a feature never divides by a zero outline.
        /// </summary>
        public float SignedDistanceInside(float localX, float localZ)
        {
            if (polygon != null && polygon.IsValid)
                return polygon.SignedDistanceInside(localX, localZ);

            // Box fallback (polygon not seeded yet): distance into the axis-aligned rectangle.
            Vector3 h = BoxHalfExtents;
            float dx = h.x - Mathf.Abs(localX);
            float dz = h.z - Mathf.Abs(localZ);
            return Mathf.Min(dx, dz);
        }

        /// <summary>
        /// Axis-aligned local-space bounds of the feature volume: XZ from the outline (so the voxel
        /// walk covers the real shape), Y spanning the full Height. Used by the mesher for its walk
        /// extent.
        /// </summary>
        public Bounds ComputeLocalBounds()
        {
            Vector3 h = BoxHalfExtents;
            if (polygon != null && polygon.IsValid)
            {
                Bounds poly = polygon.ComputeLocalBounds();
                return new Bounds(
                    new Vector3(poly.center.x, 0f, poly.center.z),
                    new Vector3(poly.size.x, height, poly.size.z));
            }
            return new Bounds(Vector3.zero, new Vector3(width, height, breadth));
        }

        // -------------------------------------------------------------------------
        // Migration from the old serialized layout.
        // -------------------------------------------------------------------------

        /// <summary>
        /// One-time upgrade from the pre-rewrite spawner fields (boxHalfExtents + FootprintShape +
        /// footprintComplexity + a loose FeaturePolygon). Maps the old single complexity dial onto the
        /// new explicit knobs so existing scenes keep a comparable shape. Safe to call repeatedly.
        /// </summary>
        public void MigrateFromLegacy(Vector3 legacyBoxHalfExtents, int legacyShape,
                                      float legacyComplexity, FeaturePolygon legacyPolygon)
        {
            width = Mathf.Max(2f, legacyBoxHalfExtents.x * 2f);
            height = Mathf.Max(2f, legacyBoxHalfExtents.y * 2f);
            breadth = Mathf.Max(2f, legacyBoxHalfExtents.z * 2f);

            mode = legacyShape == 1 ? FootprintMode.Noise : FootprintMode.Polygon;

            if (legacyPolygon != null && legacyPolygon.IsValid)
            {
                polygon ??= new FeaturePolygon();
                polygon.CopyFrom(legacyPolygon);
            }

            // Old complexity ran 1 (clean circle) → 10 (wild). Spread it across the explicit knobs.
            noise ??= new FootprintNoise();
            float c = Mathf.Clamp01((Mathf.Clamp(legacyComplexity, 1f, 10f) - 1f) / 9f);
            noise.resolution = Mathf.RoundToInt(Mathf.Lerp(20f, 64f, c));
            noise.lobeFrequency = Mathf.Lerp(1.5f, 5f, c);
            noise.lobeAmplitude = Mathf.Lerp(0.05f, 0.7f, c);
            noise.detailOctaves = Mathf.RoundToInt(Mathf.Lerp(1f, 4f, c));
            noise.detailGain = 0.5f;
            noise.irregularity = Mathf.Lerp(0f, 0.6f, c);
            noise.cornerSharpness = Mathf.Lerp(0f, 0.4f, c);
        }
    }
}
