using System;
using UnityEngine;

[CreateAssetMenu(fileName = "WorldStreamingConfig", menuName = "World Streaming/Config")]
public class WorldStreamingConfig : ScriptableObject
{
    [Header("Grid Settings")]
    [Tooltip("Size of each chunk in world units (X = width, Y = depth)")]
    public Vector2 chunkSize = new Vector2(256f, 256f);

    [Tooltip("Number of chunks in each direction (X columns, Y rows)")]
    public Vector2Int gridDimensions = new Vector2Int(4, 4);

    [Tooltip("World-space position of the grid's bottom-left corner")]
    public Vector3 worldOrigin = Vector3.zero;

    [Header("Streaming Settings")]
    [Tooltip("How many chunks around the player to keep loaded (1 = 3x3 grid, 2 = 5x5 grid)")]
    [Range(1, 4)]
    public int loadRadius = 1;

    [Tooltip("Seconds to wait before unloading a chunk no player needs (prevents thrashing)")]
    public float unloadGracePeriod = 10f;

    [Header("Chunk Data (auto-generated by WorldChunker)")]
    public ChunkInfo[] chunks;

    /// <summary>
    /// Converts a world position to the chunk grid coordinate that contains it.
    /// </summary>
    public Vector2Int WorldToChunkCoord(Vector3 worldPos)
    {
        float relX = worldPos.x - worldOrigin.x;
        float relZ = worldPos.z - worldOrigin.z;

        int cx = Mathf.FloorToInt(relX / chunkSize.x);
        int cy = Mathf.FloorToInt(relZ / chunkSize.y);

        cx = Mathf.Clamp(cx, 0, gridDimensions.x - 1);
        cy = Mathf.Clamp(cy, 0, gridDimensions.y - 1);

        return new Vector2Int(cx, cy);
    }

    /// <summary>
    /// Gets the world-space origin for the chunk at the given grid coordinate.
    /// </summary>
    public Vector3 ChunkToWorldPosition(Vector2Int coord)
    {
        return new Vector3(
            worldOrigin.x + coord.x * chunkSize.x,
            worldOrigin.y,
            worldOrigin.z + coord.y * chunkSize.y
        );
    }

    /// <summary>
    /// Gets the ChunkInfo for a given grid coordinate, or null if out of bounds.
    /// </summary>
    public ChunkInfo? GetChunk(Vector2Int coord)
    {
        if (chunks == null) return null;

        foreach (var chunk in chunks)
        {
            if (chunk.gridCoord == coord)
                return chunk;
        }

        return null;
    }

    /// <summary>
    /// Returns true if the coordinate is within the grid bounds.
    /// </summary>
    public bool IsValidCoord(Vector2Int coord)
    {
        return coord.x >= 0 && coord.x < gridDimensions.x
            && coord.y >= 0 && coord.y < gridDimensions.y;
    }
}

[Serializable]
public struct ChunkInfo
{
    public Vector2Int gridCoord;
    public string sceneName;
    public string scenePath; // full asset path, e.g. Assets/Scenes/Chunks/Chunk_0_0.unity
    public Bounds worldBounds;
    public bool hasTerrain;
}
