"""Make the component library browsable in Blender's Asset Browser.

    python _assets.py [--blender <path-to-blender.exe>] [--only <relative/path.blend> ...]

Every component file under `components/` holds one part FAMILY, with its VARIATIONS as
`Coll_<Family>_<Variant>` collections. This marks each such collection as an asset, files it in a
catalogue `<Category>/<Family>` (category = the folder under components/), gives it a
description, and asks Blender for a preview. It also writes `blender_assets.cats.txt` at the
library root, the file the Asset Browser reads catalogues from. Register this folder once in
Blender (Preferences > File Paths > Asset Libraries) and every part can be dragged into a scene.

Dual-purpose like index_library.py: run under plain Python it drives Blender over each file;
run inside Blender (`--background <file> --python _assets.py -- --mark`) it marks that file.
Re-running is safe: marking is idempotent and only asset metadata changes — no geometry.

Catalogue UUIDs are derived from the catalogue path (uuid5), so every run and every machine
agrees on them without a registry.
"""

import os
import re
import subprocess
import sys
import uuid

LIB_ROOT = os.path.dirname(os.path.abspath(__file__))
COMPONENTS = os.path.join(LIB_ROOT, "components")
CATS_FILE = os.path.join(LIB_ROOT, "blender_assets.cats.txt")
NAMESPACE = uuid.UUID("6f1c2a52-4d1e-4b8a-9d3a-5a0e7c2b9f10")   # fixed: stable catalogue ids
COLL = re.compile(r"^Coll_([A-Za-z0-9]+)_([A-Za-z0-9]+)$")
DEFAULT_BLENDER = r"C:\Program Files\Blender Foundation\Blender 5.2\blender.exe"


def words(camel):
    return re.sub(r"(?<=[a-z0-9])(?=[A-Z])", " ", camel)


def catalog_path(category, family):
    return "%s/%s" % (words(category.title()), words(family))


def catalog_id(path):
    return str(uuid.uuid5(NAMESPACE, path))


# ── inside Blender ───────────────────────────────────────────────────────────

def mark_open_file(category):
    import bpy
    marked, no_preview = [], []
    for coll in bpy.data.collections:
        m = COLL.match(coll.name)
        if not m:
            continue
        family, variant = m.groups()
        path = catalog_path(category, family)
        if coll.asset_data is None:
            coll.asset_mark()
        coll.asset_data.catalog_id = catalog_id(path)
        coll.asset_data.description = "%s — %s variation (%s)" % (words(family), words(variant), category)
        for tag in (category, family, variant):
            if tag not in [t.name for t in coll.asset_data.tags]:
                coll.asset_data.tags.new(tag)
        try:
            coll.asset_generate_preview()
        except RuntimeError as err:          # background Blender may have no GPU context
            no_preview.append("%s (%s)" % (coll.name, err))
        marked.append("%s\t%s" % (coll.name, path))
    bpy.ops.wm.save_mainfile()
    for line in marked:
        print("MARKED\t" + line)
    for line in no_preview:
        print("NOPREVIEW\t" + line)


# ── driver ───────────────────────────────────────────────────────────────────

def component_files(only):
    for root, _, files in os.walk(COMPONENTS):
        for f in sorted(files):
            if f.endswith(".blend"):
                rel = os.path.relpath(os.path.join(root, f), LIB_ROOT).replace("\\", "/")
                if not only or rel in only:
                    yield rel


def existing_catalogs():
    """Catalogue paths already in the file — kept when only some files are (re)marked."""
    if not os.path.exists(CATS_FILE):
        return set()
    with open(CATS_FILE, encoding="utf-8") as fh:
        return {l.split(":")[1] for l in fh if l.count(":") >= 2 and not l.startswith("#")}


def write_catalogs(paths):
    lines = ["# This is an Asset Catalog Definition file for Blender.",
             "# Generated by _assets.py from the components/ folder — do not hand-edit.",
             "", "VERSION 1", ""]
    parents = set()
    for p in paths:
        parts = p.split("/")
        for i in range(1, len(parts)):
            parents.add("/".join(parts[:i]))
    for p in sorted(set(paths) | parents):
        lines.append("%s:%s:%s" % (catalog_id(p), p, p.replace("/", "-")))
    with open(CATS_FILE, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines) + "\n")


def main(argv):
    blender = argv[argv.index("--blender") + 1] if "--blender" in argv else DEFAULT_BLENDER
    only = set(argv[argv.index("--only") + 1:]) if "--only" in argv else set()
    paths, failed = [], []
    for rel in component_files(only):
        category = rel.split("/")[1]
        proc = subprocess.run([blender, "--background", os.path.join(LIB_ROOT, rel), "--python",
                               os.path.abspath(__file__), "--", "--mark", category],
                              capture_output=True, text=True, encoding="utf-8", errors="replace")
        rows = [l for l in proc.stdout.splitlines() if l.startswith(("MARKED", "NOPREVIEW"))]
        if proc.returncode != 0 or not any(r.startswith("MARKED") for r in rows):
            failed.append(rel)
            print("FAILED  %s\n%s" % (rel, proc.stderr[-800:]))
            continue
        for r in rows:
            if r.startswith("MARKED"):
                paths.append(r.split("\t")[2])
        print("%-55s %d variation(s)%s" % (rel, sum(r.startswith("MARKED") for r in rows),
                                           "" if not any(r.startswith("NOPREVIEW") for r in rows)
                                           else "  (no preview in background)"))
    # a partial run adds its catalogues to the existing ones; a full run rewrites from scratch
    all_paths = set(paths) if not only else existing_catalogs() | set(paths)
    write_catalogs(all_paths)
    print("wrote %s (%d catalogues)" % (CATS_FILE, len(all_paths)))
    if failed:
        raise SystemExit("%d file(s) failed: %s" % (len(failed), ", ".join(failed)))


if "--mark" in sys.argv:
    mark_open_file(sys.argv[sys.argv.index("--mark") + 1])
elif __name__ == "__main__":
    main(sys.argv[1:])
